[build]
  publish = "."
  functions = "netlify/edge-functions"

[[redirects]]
  from = "/api/accounts"
  to = "/.netlify/edge-functions/accounts"
  status = 200

[[redirects]] # Add this new redirect for the test function
  from = "/hello"
  to = "/.netlify/edge-functions/hello"
  status = 200
